"""Render site/index.html and the per-platform instruction files from canonical sources.

The project instructions are split into a shared, platform-neutral core
(``platform-guide/project-instructions-core.md``) plus one small delta per platform
(``platform-guide/platform-delta-{claude,chatgpt,gemini}.md``). This script assembles
core + delta into:

  1. Three copy-blocks injected into ``site/index.html`` (one per platform tab).
  2. Three committed files ``platform-guide/project-instructions-{platform}.md`` — what
     the setup guides link to and what ships in the downloadable zip.

Stdlib only. Run after editing the core, any delta, or a message template:
    python site/build_site.py
The rendered index.html and the assembled per-platform files are committed; do not
hand-edit them (or the INJECT regions). Edit the core / delta / template sources instead.
"""

from __future__ import annotations

import html as html_mod
import re
from pathlib import Path

# (key, display label, where to paste it) — drives the tabs, injects, and md headers.
PLATFORMS = [
    ("claude", "Claude", "your project's **Project Instructions**"),
    ("chatgpt", "ChatGPT", "your project's **Project Instructions**"),
    ("gemini", "Gemini", "the notebook's **⋮ menu → Notebook settings → Instructions**"),
]

# Message templates: (source filename, marker name).
MESSAGE_BLOCKS = [
    ("kickoff-template.md", "kickoff"),
    ("interview-prep-template.md", "interview-prep"),
]

_GEN_NOTE = (
    "<!-- GENERATED by site/build_site.py — do not edit by hand. "
    "Edit the core / delta sources instead. -->"
)


def extract_below_divider(md: str) -> str:
    """Return everything after the first line that is exactly '---', stripped."""
    lines = md.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == "---":
            return "\n".join(lines[i + 1 :]).strip()
    raise ValueError("no '---' divider found")


def extract_message_body(md: str) -> str:
    """Return the text between the first and second lines that are exactly '---'."""
    lines = md.splitlines()
    idx = [i for i, line in enumerate(lines) if line.strip() == "---"]
    if len(idx) < 2:
        raise ValueError("expected two '---' fences")
    return "\n".join(lines[idx[0] + 1 : idx[1]]).strip()


def assemble_instructions(guide_dir: Path, platform_key: str) -> str:
    """Assemble the shared core + a platform delta into one instruction block."""
    core = extract_below_divider(
        (guide_dir / "project-instructions-core.md").read_text(encoding="utf-8")
    )
    delta = extract_below_divider(
        (guide_dir / f"platform-delta-{platform_key}.md").read_text(encoding="utf-8")
    )
    return f"{core}\n\n{delta}"


def assembled_md(guide_dir: Path, platform_key: str, label: str, paste_location: str) -> str:
    """Full contents of the committed per-platform instruction file (with paste header)."""
    body = assemble_instructions(guide_dir, platform_key)
    return (
        f"# Job Application Assistant — Project Instructions ({label})\n\n"
        f"{_GEN_NOTE}\n\n"
        f"> Paste everything below the divider into {paste_location}. "
        f"No edits needed — your name and details come from your uploaded files.\n\n"
        f"---\n\n"
        f"{body}\n"
    )


def render_block(text: str) -> str:
    """Wrap escaped text in a <pre> the copy JS reads via innerText."""
    return f'<pre class="paste-block">{html_mod.escape(text)}</pre>'


def inject(html: str, name: str, block_html: str) -> str:
    """Replace the content between the named INJECT markers; idempotent."""
    pattern = re.compile(
        rf"(<!-- INJECT:{re.escape(name)} -->).*?(<!-- /INJECT:{re.escape(name)} -->)",
        re.DOTALL,
    )
    if not pattern.search(html):
        raise ValueError(f"marker for {name!r} not found in index.html")
    return pattern.sub(lambda m: m.group(1) + block_html + m.group(2), html, count=1)


def build(project_dir: Path) -> str:
    """Read index.html + all sources, return rendered HTML with every block injected."""
    html = (project_dir / "site" / "index.html").read_text(encoding="utf-8")
    guide_dir = project_dir / "platform-guide"
    for key, _label, _loc in PLATFORMS:
        text = assemble_instructions(guide_dir, key)
        html = inject(html, f"project-instructions-{key}", render_block(text))
    for filename, name in MESSAGE_BLOCKS:
        md = (guide_dir / filename).read_text(encoding="utf-8")
        html = inject(html, name, render_block(extract_message_body(md)))
    return html


def main() -> None:
    project_dir = Path(__file__).resolve().parent.parent
    guide_dir = project_dir / "platform-guide"
    (project_dir / "site" / "index.html").write_text(build(project_dir), encoding="utf-8")
    for key, label, loc in PLATFORMS:
        (guide_dir / f"project-instructions-{key}.md").write_text(
            assembled_md(guide_dir, key, label, loc), encoding="utf-8"
        )
    print("rendered site/index.html + per-platform instruction files")


if __name__ == "__main__":
    main()
